version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/app/src
      - ./server/node_modules:/app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./.env
