version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/app/src
      - ./server/node_modules:/app/node_modules
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - ./.env
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - ./.env
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - "27017:27017"

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/src:/app/src
      - ./web/node_modules:/app/node_modules
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - ./.env

volumes:
  data:
    name: data